default['minidlna']['media_dir'] = '/var/lib/minidlna'
default['minidlna']['port'] = '8200'
default['minidlna']['serial'] = '12345678'
default['minidlna']['model_number'] = '1'
default['minidlna']['album_art_names'] = 'Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg'
